# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Check code sanity

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: 'setup env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        env:
          NEXTAUTH_URL: "http://localhost:3000"
          NEXTAUTH_SECRET: "socasome5aefDaUG7somelop"
          EMAIL_SERVER: smtp://example@test:zPrh&somezhoho@xyz.zoho.com:987
          EMAIL_FROM: no-reply@example.com
          MONGODB_URI: mongodb://example:pass@ac-8hnubn-s
          REALM_APP_ID: example-next-me
          MONGODB_DB: sparked-next
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn build
